config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :destroy]

  get 'dashboard', to: "users#dashboard", as: "dashboard"

  resources :services, only: [ :index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [ :new, :create ]
    resources :comments, only: [ :create ]
  end

  resources :bookings, only: [ :update ] do
    resources :reviews, only: [:create]
  end

  root to: 'pages#home'
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :bookings, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  mount_uploader :photo, PhotoUploader
  geocoded_by :location

  validates :title, presence: :true, uniqueness: true
  validates :description, presence: :true
  validates :category, presence: :true
  validates :location, presence: :true
  validates :years_experience, presence: :true
  validates :price, presence: :true

  after_validation :geocode, if: :location_changed?

  def self.search(search)
    if search
      # where(['location LIKE ?', "%#{search}%"])
      near("#{search}", 50)
    else
      all
    end
  end

  def booked_by_user?(user)
    check_arrray = []
    self.bookings.each do |booking|
      (booking.user == user) && (booking.status == 'accepted') ? check_arrray << true : check_arrray << false
    end
    return check_arrray.any?
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_service, only: [:show, :edit, :update]

  def index
    @services = Service.search(params[:search])
    @services_map = Service.search(params[:search]).where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@services_map) do |service, marker|
      marker.lat service.latitude
      marker.lng service.longitude
    end
  end

  def show
    @user = @service.user
    @booking = Booking.new
    @bookings = @service.bookings
    @comment = Comment.new
    @comments = @service.comments.sort_by { |comment| comment.created_at }.reverse

    @hash = Gmaps4rails.build_markers(@service) do |service, marker|
      marker.lat service.latitude
      marker.lng service.longitude
    end
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user

    if @service.save
      redirect_to service_path(@service)
    else
      render :new
    end
  end

  def edit
    if current_user == @service.user
    else
      redirect_to service_path(@service)
    end
  end

  def update
    if @service.update(service_params)
      redirect_to service_path(@service)
    else
      render :new
    end
  end

  private

  def service_params
    params.require(:service).permit(:title, :description, :category, :location, :equipment, :food, :price, :years_experience, :min_hour, :photo, :photo_cache)
  end

  def set_service
    @service = Service.find(params[:id])
  end
end

app/views/services/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-2 col-lg-5 col-lg-offset-1">
      <h2>Create a new Class</h2>
      <%= simple_form_for(@service) do |f| %>
        <div class="form-inputs">
          <%= f.input :title %>
          <%= f.input :description, as: :text, :input_html => {:rows => 5} %>
          <%= f.input :category %>
          <%= f.input :location, input_html: {class: "autocomplete-location"} %>
          <%= f.input :equipment, placeholder: "What equipment do you provide, if any ?" %>
          <%= f.input :food, placeholder: "What food do you provide, if any ?" %>
          <%= f.input :price, label: "Price per hour" %>
          <%= f.input :min_hour, required: true, label: "Session length (in hours)" %>
          <%= f.input :years_experience %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Create" %>
        </div>
      <% end %>
    </div>

    <div class="col-xs-12 col-sm-4 col-sm-offset-2 col-lg-5 col-lg-offset-1">
      <h2>How it works</h2>
      <div class="box-service">
        <strong>1 - Create your class</strong><br>
        <p> Anyone can register on the platform, but during the beta period, we prefer to personally review every service provider application in order to offer the best experience to our users.</p>
        <div class="text-center" id="icon-big">
          <i class="fa fa-magic" aria-hidden="true"></i>
        </div>
      </div>

      <div class="box-service">
        <strong>2 - Get your student</strong><br>
        <p> Find the perfect local for your need, request a booking on one of their packages. </p>
        <div class="text-center" id="icon-big">
          <i class="fa fa-graduation-cap" aria-hidden="true"></i>
        </div>
      </div>

      <div class="box-service">
        <strong>3 - Get money </strong><br>
        <p> Time to go surfing! Meet your local service provider, surf together, take pictures, share the waves, the local culture and an awesome experience </p>
        <div class="text-center" id="icon-big">
          <i class="fa fa-money" aria-hidden="true"></i>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<% content_for :meta_title, "Poseidon - All the surf class in one palce" %>


<div id="map" style="width: 100%; height: 300px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

<div class="container padded">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <div class="search">
        <div class="form-group-index">
          <%= form_tag services_path, method: :get, class: "form-group-navbar-home" do %>
              <%= text_field_tag :search, params[:search], class:'autocomplete-location form-control searchbar-index', placeholder: "Where would you like to surf ?" %>
              <%= button_tag "Search", :name => nil, class:"input-group-addon-index form-group-navbar-button" do %>
                <i class="fa fa-search" aria-hidden="true"></i>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row group">
    <% @services.each do |service| %>
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <%= link_to service_path(service.id) do %>
      <article class="post">
        <div class="card-author">
          <% if service.photo? %>
          <div class="post-author" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path service.photo, height: 300, width: 400, crop: :fill %>')">
            <% else %>
            <div class="post-author">
              <% end %>
              <!-- à rajouter l'avatar de l'user class deja ajouter ajouter l'effet float -->
              <% if service.user.facebook_picture_url? %>
              <%= cl_image_tag service.user.facebook_picture_url %>
              <% end %>
              <div class="author-details">
                <span class="author-name">
                  <% if service.user.last_name? %>
                  <%= service.user.first_name %> <%= service.user.last_name %>
                  <% else %>
                  <%= service.user.email %>
                  <% end %>
                </span>
                <i class="author-position"></i>
              </div>
            </div>
          </div>
          <div class="card-content">
            <ul>
              <li><%= service.category %></li>
            </ul>
            <h2><%= service.title %></h2>
            <p class="description">
              <%= service.description %>
            </p>
            <span class="read-time">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <%= service.location %> - <%= service.price %>€/hours - minimum <%= service.min_hour %>hours.
            </span>
          </div>
        </article>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>

app/views/services/new.html.erb
<%= render 'form' %>

app/views/services/show.html.erb
<% content_for :meta_title, "Poseidon - #{@service.title}" %>
<% content_for :meta_description, @service.description %>
<% content_for :meta_image, cloudinary_url(@service.photo.path) %>


<div class="container">
  <div class="show-service">
    <div class="row" id="service-info">
      <div class="col-sm-12 col-md-6 col-lg-7">
        <div class="body-content">
          <div class="title-description">
            <h1><%= @service.title %></h1>
            <%= @service.location %> · <%= @service.category %>
            <% if current_user == @service.user %>
            <div class="edit-service">
              <%= link_to "Edit", edit_service_path(@service), class: "btn btn-primary"%>
            </div>
            <% end %>
          </div>
          <div class="info-service-description">
            <div class="row">
              <div class="col-xs-12 col-sm-2 profile-picture">
              <%= link_to user_path(@service.user_id) do %>
                <%= cl_image_tag @service.user.facebook_picture_url, class: "img-circle" %>
                <% end %>
              </div>
              <div class="col-xs-12 col-sm-9">
                <div class="details-profile">
                  Hosted by <%= @service.user.first_name %><br>
                  <% if @service.equipment != ""  %>
                    Equipment provided (see below)<br>
                  <% else %>
                    Equipment not provided<br>
                  <% end %>
                  <%= @service.min_hour %> h session (minimum) <br>
                  Languages spoken: <%= @user.language %><br>
                </div>
              </div>
            </div>
          </div>
          <div class="box-service">
            <strong>Description</strong><br>
            <%= @service.description %>
          </div>
          <div class="box-service">
            <strong>Where I'll provide</strong><br>
            Equipment <br>
            <%= @service.equipment %><br><br>

            Food<br>
            <%= @service.food %>

          </div>
          <div class="last-box">
            <strong>Where we'll meet</strong><br>
            <div id="map" class="add-margin" style="width: 100%; height: 400px;"></div>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-4 col-md-offset-1" id="col-info">
        <div id="one">
          <div id="card-image">
            <div class="info-content">
              <div class="img-service">
                <%= cl_image_tag @service.photo, height: 500, width: 400, crop: :fill %>
              </div>
              <p><strong>€<%= @service.price %></strong> <span class="font-small">&nbsp;per person</span></p>
              <p><%= @service.comments.count %> reviews</p>
              <p> Already <strong><%= @service.bookings.count %> people</strong> have booked this class</p>
              <p><%= link_to "Book", new_service_booking_path(@service), class: "btn btn-primary btn-full-width"%></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Chat box -->
  <div class="comment-box" id="two">
  <strong>Reviews</strong>
    <% if @service.booked_by_user?(current_user) %>
      <div class="row">
        <div class="col-sm-12 col-md-6 col-lg-7">

          <%= simple_form_for([@service, @comment]) do |f| %>
          <div class="form-inputs">
            <%= f.input :content, label: false, placeholder: "Write a review..." %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Send" %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
    <div class="row">
      <div class="col-sm-12 col-md-6 col-lg-7" id="comments">

        <div class="board-outline">

          <% @comments.each do |comment| %>

          <div class="message">

            <% if comment.user.facebook_picture_url? %>
            <%= image_tag comment.user.facebook_picture_url, { class: "avatar-large img-circle" }%>
            <% else %>
            <div class="message-empty-img"></div>
            <% end %>

            <div class="message-name">
              <h3><%= comment.user.first_name %> <%= comment.user.last_name %></h3>
              <p><%= comment.created_at.strftime('%a %d %b %Y')  %></p>
            </div>
            <div class="message-body">
              <p>
                <% if comment.user == current_user %>
                <div class="text-green">
                  <%= comment.content %>
                </div>
                <% else %>
                <div>
                  <%= comment.content %>
                </div>
                <% end %>
              </p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Map -->

<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).ready(function() {
var handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map' } }, function() {
markers = handler.addMarkers(<%= raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
if (markers.length == 0) {
handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
}
});
});

const boxComment = document.getElementById("two").offsetHeight;

$(function() {
$("#one").sticky({bottomSpacing: 130 + boxComment});
});
<% end %>
<% end %>