config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :destroy]

  get 'dashboard', to: "users#dashboard", as: "dashboard"

  resources :services, only: [ :index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [ :new, :create ]
    resources :comments, only: [ :create ]
  end

  resources :bookings, only: [ :update ] do
    resources :reviews, only: [:create]
  end

  root to: 'pages#home'
end

app/views/shared/_banner.html.erb
<!-- How to use  -->
<!-- with a tag services.photo -->
<!-- render 'shared/banner', image: cl_image_path(@service.photo, {height: 300, width: 400, crop: :fill}) -->
<!-- with a url  -->
<!-- render 'shared/banner', image: "http://res.cloudinary.com/dzly3hnxk/image/upload/c_scale,w_2000/v1502443713/pexels-photo-509791_noiet8.jpg" -->

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(161,196,253,0.6) 0%, rgba(194,233,251,0.6) 50%), url(' <%=  image %>');">
  <div class="banner-content text-center">
    <!-- <h1>Mister Cocktail</h1>
    <p>try a new one everyday and become ALCOOL ADDICT</p> -->
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <h1 class="footer-logo">POSEIDON</h1>
  <div class="footer-copyright">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag 'http://res.cloudinary.com/dyub4bz6x/image/upload/v1503066686/scallop_fo7kye.svg' %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Create a class", new_service_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Classes", services_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link"  %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
        <% if current_user.facebook_picture_url.nil? %>
          <%= cl_image_tag(("j0eg4xw5jsjkktiair0f.jpg"), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown") %>
        <% else %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Create a class", new_service_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Classes", services_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>