config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update, :destroy]

  get 'dashboard', to: "users#dashboard", as: "dashboard"

  resources :services, only: [ :index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [ :new, :create ]
    resources :comments, only: [ :create ]
  end

  resources :bookings, only: [ :update ] do
    resources :reviews, only: [:create]
  end

  root to: 'pages#home'
end

app/views/pages/home.html.erb
<!-- banner video -->
<header class="heropanel--video" data-vide-bg="mp4: http://res.cloudinary.com/dyub4bz6x/video/upload/v1502726560/covervid_sfoigx.mp4", poster: https://static.pexels.com/photos/342469/pexels-photo-342469.jpeg data-vide-options="posterType: png, loop: true, muted: true, position: 50% 50%">
  <div class="heropanel__content">
    <h1>POSEIDON</h1>
  </div>
  <!-- searchbar -->
  <div class="search">
    <div class="form-group">
      <%= form_tag "/services", method: :get, class: "form-group-navbar-home"  do %>
      <%= text_field_tag :search, "", class:'autocomplete-location form-control searchbar' , placeholder: "Where would you like to surf ?"  %>
      <%= button_tag "search", name: nil, class:"input-group-addon form-group-navbar-button" do %>
      <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
      <% end %>
    </div>
  </div>
</header>
<div class="container padded">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-md-offset-2">
      <h6>C H E C K - O U R - L A S T - C L A S S E S</h6>
    </div>
  </div>
  <ul class="cards">
    <% @services.last(3).each do |s| %>
    <li class="cards_item">
      <div class="card">


        <div class="col-xs-12 col-sm-3 card-illustration" style="background-image: url('<%= cl_image_path s.photo_url, height: 150, width: 300, crop: :fill %>');">


        </div>
        <div class="card_content">
          <div class="row top-card">
            <div class="post-author col-sm-3">
              <% if s.user.facebook_picture_url?%>
              <%= link_to user_path(s.user) do %>
              <%= cl_image_tag s.user.facebook_picture_url %>
              <% end %>
              <% end %>
            </div>
            <div class="col-sm-9">
              <h2 class="card_heading "><%= s.title %>
              <h6 class="price"><%= s.price %>€  -  <i class="fa fa-map-marker" aria-hidden="true"></i>
              <%= s.location %></h6>
            </div>
          </div>
          <p><%= s.description %></p>
          <%= link_to "More infos", service_path(s), class:"btn-primary btn-card" %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>